"""empty message

Revision ID: 54023029a87b
Revises: 988b36ef4056
Create Date: 2024-03-23 19:41:20.740634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54023029a87b'
down_revision = '988b36ef4056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_invitation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opponent', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('opponent2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('opponent_img', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('opponent_img2', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_invitation', schema=None) as batch_op:
        batch_op.drop_column('opponent_img2')
        batch_op.drop_column('opponent_img')
        batch_op.drop_column('opponent2')
        batch_op.drop_column('opponent')

    # ### end Alembic commands ###
