"""empty message

Revision ID: 876e0f6bd282
Revises: 948226d8b8b8
Create Date: 2024-03-27 05:57:43.740108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876e0f6bd282'
down_revision = '948226d8b8b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_post',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('place', sa.String(length=400), nullable=True),
    sa.Column('caption', sa.String(length=1000), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('opponent', sa.String(), nullable=True),
    sa.Column('opponent2', sa.String(), nullable=True),
    sa.Column('opponent_img', sa.String(length=300), nullable=True),
    sa.Column('opponent_img2', sa.String(length=300), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_post')
    # ### end Alembic commands ###
