"""empty message

Revision ID: 9af72eac147d
Revises: e9157c80c853
Create Date: 2024-03-20 18:20:57.723133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9af72eac147d'
down_revision = 'e9157c80c853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('save_game',
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('opponent', sa.String(), nullable=False),
    sa.Column('opponent2', sa.String(), nullable=False),
    sa.Column('opponent_img', sa.String(length=300), nullable=False),
    sa.Column('opponent_img2', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('save_game')
    # ### end Alembic commands ###
